databaseChangeLog:
  - changeSet:
      id: add-login-security-fields
      author: Omar
      changes:
        - addColumn:
            tableName: users
            columns:
              - column:
                  name: failed_attempts
                  type: INT
                  defaultValueNumeric: 0
              - column:
                  name: account_locked
                  type: BOOLEAN
                  defaultValueBoolean: false
              - column:
                  name: lock_time
                  type: TIMESTAMP